language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install rgl RANN igraph filehash digest testthat
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get install cmtk --no-install-recommends
install:
  - ./travis-tool.sh install_deps
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - secure: pGh2sZTLYXbvjnOHFN5rcT+H/hNAlg7o325Pa1RQdjmtK0CWjTh0j/tomIeI9LkFOEgaglUIKQmjAOZWXWyhI4ig2x5L6sYEDY491LYHridGsbBcFL/ND3H/zaBZ0qoh3Yofj37Y2fM6lp7W10Y4WueFxUmwncbJRT/Xrai/n/c=
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - DISPLAY=:99.0
after_success:
  - chmod 755 ./travisbuildflycircuit.sh
  - ./travisbuildflycircuit.sh
